# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven + Tests Artifact

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        java-version: [17, 19]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    # Caching Mechanism
#    - name: Cache local Maven repository
#      uses: actions/cache@v4
#      with:
#        path: ~/.m2/repository
#        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#        restore-keys: |
#          ${{ runner.os }}-maven-

    - name: Set Database Secrets
      run: |
        sed -i 's/##db.username##/${{ secrets.DB_USERNAME }}/g' config/application.yaml
        sed -i 's/##db.password##/${{ secrets.DB_PASSWORD }}/g' config/application.yaml

    - name: Build with Maven
      run: mvn -B -ntp clean install

    - name: Archive Test Reports
      if: always() # Always run even if the build fails
      uses: actions/upload-artifact@v4.4.0
      with:
        name: test-reports
        path: target/surefire-reports/

    # Upload the JaCoCo code coverage report
    - name: Archive Code Coverage Report
      if: always()  # Run this step even if previous steps fail
      uses: actions/upload-artifact@v4.4.0
      with:
        name: coverage-report
        path: target/site/jacoco/

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: |
          target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 70
        min-coverage-changed-files: 90
        title: '# :lobster: Coverage Report'
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

    - name: Fail PR if overall coverage is less than 70%
      if: ${{ github.event_name == 'pull_request' && steps.jacoco.outputs.coverage-overall < 70.0 }}
      uses: actions/github-script@v7.0.1
      with:
        script: |
          core.setFailed('Overall coverage is less than 70%!')
